version: '3'
services:
  app:
    build: .
    volumes:
      - ./django-project/:/app/
    working_dir: /app/
    command: ["bash","run.sh"]
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    
